// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: borrow_requests.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const cancelBorrowRequest = `-- name: CancelBorrowRequest :one
UPDATE borrow_requests
SET status = 'cancelled'
WHERE id = $1
RETURNING id, borrower_name, borrower_telegram_id, committee_id, borrow_photo_url, return_photo_url, expected_return_at, remarks, status, borrowed_at
`

func (q *Queries) CancelBorrowRequest(ctx context.Context, id int32) (BorrowRequest, error) {
	row := q.db.QueryRow(ctx, cancelBorrowRequest, id)
	var i BorrowRequest
	err := row.Scan(
		&i.ID,
		&i.BorrowerName,
		&i.BorrowerTelegramID,
		&i.CommitteeID,
		&i.BorrowPhotoUrl,
		&i.ReturnPhotoUrl,
		&i.ExpectedReturnAt,
		&i.Remarks,
		&i.Status,
		&i.BorrowedAt,
	)
	return i, err
}

const createBorrowRequest = `-- name: CreateBorrowRequest :one
INSERT INTO borrow_requests (
    borrower_name,
    borrower_telegram_id,
    committee_id,
    borrow_photo_url,
    expected_return_at,
    remarks
) VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, borrower_name, borrower_telegram_id, committee_id, borrow_photo_url, return_photo_url, expected_return_at, remarks, status, borrowed_at
`

type CreateBorrowRequestParams struct {
	BorrowerName       string      `json:"borrower_name"`
	BorrowerTelegramID int64       `json:"borrower_telegram_id"`
	CommitteeID        int32       `json:"committee_id"`
	BorrowPhotoUrl     string      `json:"borrow_photo_url"`
	ExpectedReturnAt   pgtype.Date `json:"expected_return_at"`
	Remarks            pgtype.Text `json:"remarks"`
}

func (q *Queries) CreateBorrowRequest(ctx context.Context, arg CreateBorrowRequestParams) (BorrowRequest, error) {
	row := q.db.QueryRow(ctx, createBorrowRequest,
		arg.BorrowerName,
		arg.BorrowerTelegramID,
		arg.CommitteeID,
		arg.BorrowPhotoUrl,
		arg.ExpectedReturnAt,
		arg.Remarks,
	)
	var i BorrowRequest
	err := row.Scan(
		&i.ID,
		&i.BorrowerName,
		&i.BorrowerTelegramID,
		&i.CommitteeID,
		&i.BorrowPhotoUrl,
		&i.ReturnPhotoUrl,
		&i.ExpectedReturnAt,
		&i.Remarks,
		&i.Status,
		&i.BorrowedAt,
	)
	return i, err
}

const createBorrowRequestItem = `-- name: CreateBorrowRequestItem :one
INSERT INTO borrow_request_items (borrow_request_id, item_id, quantity)
VALUES ($1, $2, $3)
RETURNING id, borrow_request_id, item_id, quantity, returned_quantity
`

type CreateBorrowRequestItemParams struct {
	BorrowRequestID int32 `json:"borrow_request_id"`
	ItemID          int32 `json:"item_id"`
	Quantity        int32 `json:"quantity"`
}

func (q *Queries) CreateBorrowRequestItem(ctx context.Context, arg CreateBorrowRequestItemParams) (BorrowRequestItem, error) {
	row := q.db.QueryRow(ctx, createBorrowRequestItem, arg.BorrowRequestID, arg.ItemID, arg.Quantity)
	var i BorrowRequestItem
	err := row.Scan(
		&i.ID,
		&i.BorrowRequestID,
		&i.ItemID,
		&i.Quantity,
		&i.ReturnedQuantity,
	)
	return i, err
}

const getAllBorrowRequests = `-- name: GetAllBorrowRequests :many
SELECT
    br.id,
    br.borrower_name,
    br.borrower_telegram_id,
    br.committee_id,
    br.borrow_photo_url,
    br.return_photo_url,
    br.expected_return_at,
    br.remarks,
    br.status,
    br.borrowed_at
FROM borrow_requests br
ORDER BY br.borrowed_at DESC
`

func (q *Queries) GetAllBorrowRequests(ctx context.Context) ([]BorrowRequest, error) {
	rows, err := q.db.Query(ctx, getAllBorrowRequests)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BorrowRequest
	for rows.Next() {
		var i BorrowRequest
		if err := rows.Scan(
			&i.ID,
			&i.BorrowerName,
			&i.BorrowerTelegramID,
			&i.CommitteeID,
			&i.BorrowPhotoUrl,
			&i.ReturnPhotoUrl,
			&i.ExpectedReturnAt,
			&i.Remarks,
			&i.Status,
			&i.BorrowedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBorrowRequestByID = `-- name: GetBorrowRequestByID :one
SELECT
    br.id,
    br.borrower_name,
    br.borrower_telegram_id,
    br.committee_id,
    br.borrow_photo_url,
    br.return_photo_url,
    br.expected_return_at,
    br.remarks,
    br.status,
    br.borrowed_at
FROM borrow_requests br
WHERE br.id = $1
`

func (q *Queries) GetBorrowRequestByID(ctx context.Context, id int32) (BorrowRequest, error) {
	row := q.db.QueryRow(ctx, getBorrowRequestByID, id)
	var i BorrowRequest
	err := row.Scan(
		&i.ID,
		&i.BorrowerName,
		&i.BorrowerTelegramID,
		&i.CommitteeID,
		&i.BorrowPhotoUrl,
		&i.ReturnPhotoUrl,
		&i.ExpectedReturnAt,
		&i.Remarks,
		&i.Status,
		&i.BorrowedAt,
	)
	return i, err
}

const getBorrowRequestItems = `-- name: GetBorrowRequestItems :many
SELECT
    bri.id,
    bri.borrow_request_id,
    bri.item_id,
    bri.quantity,
    bri.returned_quantity
FROM borrow_request_items bri
WHERE bri.borrow_request_id = $1
`

func (q *Queries) GetBorrowRequestItems(ctx context.Context, borrowRequestID int32) ([]BorrowRequestItem, error) {
	rows, err := q.db.Query(ctx, getBorrowRequestItems, borrowRequestID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BorrowRequestItem
	for rows.Next() {
		var i BorrowRequestItem
		if err := rows.Scan(
			&i.ID,
			&i.BorrowRequestID,
			&i.ItemID,
			&i.Quantity,
			&i.ReturnedQuantity,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBorrowRequestsByCommittee = `-- name: GetBorrowRequestsByCommittee :many
SELECT
    br.id,
    br.borrower_name,
    br.borrower_telegram_id,
    br.committee_id,
    br.borrow_photo_url,
    br.return_photo_url,
    br.expected_return_at,
    br.remarks,
    br.status,
    br.borrowed_at
FROM borrow_requests br
WHERE br.committee_id = $1
ORDER BY br.borrowed_at DESC
`

func (q *Queries) GetBorrowRequestsByCommittee(ctx context.Context, committeeID int32) ([]BorrowRequest, error) {
	rows, err := q.db.Query(ctx, getBorrowRequestsByCommittee, committeeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BorrowRequest
	for rows.Next() {
		var i BorrowRequest
		if err := rows.Scan(
			&i.ID,
			&i.BorrowerName,
			&i.BorrowerTelegramID,
			&i.CommitteeID,
			&i.BorrowPhotoUrl,
			&i.ReturnPhotoUrl,
			&i.ExpectedReturnAt,
			&i.Remarks,
			&i.Status,
			&i.BorrowedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBorrowRequestsByTelegramID = `-- name: GetBorrowRequestsByTelegramID :many
SELECT
    br.id,
    br.borrower_name,
    br.borrower_telegram_id,
    br.committee_id,
    br.borrow_photo_url,
    br.return_photo_url,
    br.expected_return_at,
    br.remarks,
    br.status,
    br.borrowed_at
FROM borrow_requests br
WHERE br.borrower_telegram_id = $1
ORDER BY br.borrowed_at DESC
`

func (q *Queries) GetBorrowRequestsByTelegramID(ctx context.Context, borrowerTelegramID int64) ([]BorrowRequest, error) {
	rows, err := q.db.Query(ctx, getBorrowRequestsByTelegramID, borrowerTelegramID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BorrowRequest
	for rows.Next() {
		var i BorrowRequest
		if err := rows.Scan(
			&i.ID,
			&i.BorrowerName,
			&i.BorrowerTelegramID,
			&i.CommitteeID,
			&i.BorrowPhotoUrl,
			&i.ReturnPhotoUrl,
			&i.ExpectedReturnAt,
			&i.Remarks,
			&i.Status,
			&i.BorrowedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRecentActivity = `-- name: GetRecentActivity :many
SELECT
    br.id,
    br.borrower_name,
    br.committee_id,
    br.status,
    br.borrowed_at
FROM borrow_requests br
ORDER BY br.borrowed_at DESC
LIMIT $1
`

type GetRecentActivityRow struct {
	ID           int32              `json:"id"`
	BorrowerName string             `json:"borrower_name"`
	CommitteeID  int32              `json:"committee_id"`
	Status       string             `json:"status"`
	BorrowedAt   pgtype.Timestamptz `json:"borrowed_at"`
}

func (q *Queries) GetRecentActivity(ctx context.Context, limit int32) ([]GetRecentActivityRow, error) {
	rows, err := q.db.Query(ctx, getRecentActivity, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRecentActivityRow
	for rows.Next() {
		var i GetRecentActivityRow
		if err := rows.Scan(
			&i.ID,
			&i.BorrowerName,
			&i.CommitteeID,
			&i.Status,
			&i.BorrowedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const returnBorrowRequest = `-- name: ReturnBorrowRequest :one
UPDATE borrow_requests
SET status = 'returned',
    return_photo_url = $2
WHERE id = $1
RETURNING id, borrower_name, borrower_telegram_id, committee_id, borrow_photo_url, return_photo_url, expected_return_at, remarks, status, borrowed_at
`

type ReturnBorrowRequestParams struct {
	ID             int32  `json:"id"`
	ReturnPhotoUrl string `json:"return_photo_url"`
}

func (q *Queries) ReturnBorrowRequest(ctx context.Context, arg ReturnBorrowRequestParams) (BorrowRequest, error) {
	row := q.db.QueryRow(ctx, returnBorrowRequest, arg.ID, arg.ReturnPhotoUrl)
	var i BorrowRequest
	err := row.Scan(
		&i.ID,
		&i.BorrowerName,
		&i.BorrowerTelegramID,
		&i.CommitteeID,
		&i.BorrowPhotoUrl,
		&i.ReturnPhotoUrl,
		&i.ExpectedReturnAt,
		&i.Remarks,
		&i.Status,
		&i.BorrowedAt,
	)
	return i, err
}
