// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: committees.sql

package db

import (
	"context"
)

const getAllCommittees = `-- name: GetAllCommittees :many
SELECT id, name, created_at
FROM committees
ORDER BY name ASC
`

func (q *Queries) GetAllCommittees(ctx context.Context) ([]Committee, error) {
	rows, err := q.db.Query(ctx, getAllCommittees)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Committee
	for rows.Next() {
		var i Committee
		if err := rows.Scan(&i.ID, &i.Name, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCommitteeByID = `-- name: GetCommitteeByID :one
SELECT id, name, created_at
FROM committees
WHERE id = $1
`

func (q *Queries) GetCommitteeByID(ctx context.Context, id int32) (Committee, error) {
	row := q.db.QueryRow(ctx, getCommitteeByID, id)
	var i Committee
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}
