// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: items.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createItem = `-- name: CreateItem :one
INSERT INTO items (name, category, variant, committee_id, total_quantity, description)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, name, category, variant, committee_id, total_quantity, description, created_at, updated_at
`

type CreateItemParams struct {
	Name          string      `json:"name"`
	Category      string      `json:"category"`
	Variant       pgtype.Text `json:"variant"`
	CommitteeID   int32       `json:"committee_id"`
	TotalQuantity int32       `json:"total_quantity"`
	Description   pgtype.Text `json:"description"`
}

func (q *Queries) CreateItem(ctx context.Context, arg CreateItemParams) (Item, error) {
	row := q.db.QueryRow(ctx, createItem,
		arg.Name,
		arg.Category,
		arg.Variant,
		arg.CommitteeID,
		arg.TotalQuantity,
		arg.Description,
	)
	var i Item
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Category,
		&i.Variant,
		&i.CommitteeID,
		&i.TotalQuantity,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteItem = `-- name: DeleteItem :exec
DELETE FROM items WHERE id = $1
`

func (q *Queries) DeleteItem(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteItem, id)
	return err
}

const getAllItems = `-- name: GetAllItems :many
SELECT 
    i.id,
    i.name,
    i.category,
    i.variant,
    i.committee_id,
    i.total_quantity,
    i.description,
    i.created_at,
    i.updated_at,
    COALESCE(SUM(
        CASE
            WHEN br.status = 'active'
            THEN bri.quantity
            ELSE 0
        END
    ), 0)::int AS borrowed_quantity
FROM items i
LEFT JOIN borrow_request_items bri ON bri.item_id = i.id
LEFT JOIN borrow_requests br ON br.id = bri.borrow_request_id
GROUP BY i.id
ORDER BY i.name ASC
`

type GetAllItemsRow struct {
	ID               int32              `json:"id"`
	Name             string             `json:"name"`
	Category         string             `json:"category"`
	Variant          pgtype.Text        `json:"variant"`
	CommitteeID      int32              `json:"committee_id"`
	TotalQuantity    int32              `json:"total_quantity"`
	Description      pgtype.Text        `json:"description"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	BorrowedQuantity int32              `json:"borrowed_quantity"`
}

func (q *Queries) GetAllItems(ctx context.Context) ([]GetAllItemsRow, error) {
	rows, err := q.db.Query(ctx, getAllItems)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllItemsRow
	for rows.Next() {
		var i GetAllItemsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Category,
			&i.Variant,
			&i.CommitteeID,
			&i.TotalQuantity,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.BorrowedQuantity,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getItemBorrowHistory = `-- name: GetItemBorrowHistory :many
SELECT
    br.id,
    br.borrower_name,
    br.borrower_telegram_id,
    br.status,
    br.borrowed_at,
    br.expected_return_at,
    bri.quantity
FROM borrow_requests br
JOIN borrow_request_items bri ON bri.borrow_request_id = br.id
WHERE bri.item_id = $1
ORDER BY br.borrowed_at DESC
`

type GetItemBorrowHistoryRow struct {
	ID                 int32              `json:"id"`
	BorrowerName       string             `json:"borrower_name"`
	BorrowerTelegramID int64              `json:"borrower_telegram_id"`
	Status             string             `json:"status"`
	BorrowedAt         pgtype.Timestamptz `json:"borrowed_at"`
	ExpectedReturnAt   pgtype.Date        `json:"expected_return_at"`
	Quantity           int32              `json:"quantity"`
}

func (q *Queries) GetItemBorrowHistory(ctx context.Context, itemID int32) ([]GetItemBorrowHistoryRow, error) {
	rows, err := q.db.Query(ctx, getItemBorrowHistory, itemID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetItemBorrowHistoryRow
	for rows.Next() {
		var i GetItemBorrowHistoryRow
		if err := rows.Scan(
			&i.ID,
			&i.BorrowerName,
			&i.BorrowerTelegramID,
			&i.Status,
			&i.BorrowedAt,
			&i.ExpectedReturnAt,
			&i.Quantity,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getItemByID = `-- name: GetItemByID :one
SELECT 
    i.id,
    i.name,
    i.category,
    i.variant,
    i.committee_id,
    i.total_quantity,
    i.description,
    i.created_at,
    i.updated_at,
    COALESCE(SUM(
        CASE
            WHEN br.status = 'active'
            THEN bri.quantity
            ELSE 0
        END
    ), 0)::int AS borrowed_quantity
FROM items i
LEFT JOIN borrow_request_items bri ON bri.item_id = i.id
LEFT JOIN borrow_requests br ON br.id = bri.borrow_request_id
WHERE i.id = $1
GROUP BY i.id
`

type GetItemByIDRow struct {
	ID               int32              `json:"id"`
	Name             string             `json:"name"`
	Category         string             `json:"category"`
	Variant          pgtype.Text        `json:"variant"`
	CommitteeID      int32              `json:"committee_id"`
	TotalQuantity    int32              `json:"total_quantity"`
	Description      pgtype.Text        `json:"description"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	BorrowedQuantity int32              `json:"borrowed_quantity"`
}

func (q *Queries) GetItemByID(ctx context.Context, id int32) (GetItemByIDRow, error) {
	row := q.db.QueryRow(ctx, getItemByID, id)
	var i GetItemByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Category,
		&i.Variant,
		&i.CommitteeID,
		&i.TotalQuantity,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.BorrowedQuantity,
	)
	return i, err
}

const getItemsByCommittee = `-- name: GetItemsByCommittee :many
SELECT 
    i.id,
    i.name,
    i.category,
    i.variant,
    i.committee_id,
    i.total_quantity,
    i.description,
    i.created_at,
    i.updated_at,
    COALESCE(SUM(
        CASE
            WHEN br.status = 'active'
            THEN bri.quantity
            ELSE 0
        END
    ), 0)::int AS borrowed_quantity
FROM items i
LEFT JOIN borrow_request_items bri ON bri.item_id = i.id
LEFT JOIN borrow_requests br ON br.id = bri.borrow_request_id
WHERE i.committee_id = $1
GROUP BY i.id
ORDER BY i.name ASC
`

type GetItemsByCommitteeRow struct {
	ID               int32              `json:"id"`
	Name             string             `json:"name"`
	Category         string             `json:"category"`
	Variant          pgtype.Text        `json:"variant"`
	CommitteeID      int32              `json:"committee_id"`
	TotalQuantity    int32              `json:"total_quantity"`
	Description      pgtype.Text        `json:"description"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	BorrowedQuantity int32              `json:"borrowed_quantity"`
}

func (q *Queries) GetItemsByCommittee(ctx context.Context, committeeID int32) ([]GetItemsByCommitteeRow, error) {
	rows, err := q.db.Query(ctx, getItemsByCommittee, committeeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetItemsByCommitteeRow
	for rows.Next() {
		var i GetItemsByCommitteeRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Category,
			&i.Variant,
			&i.CommitteeID,
			&i.TotalQuantity,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.BorrowedQuantity,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateItem = `-- name: UpdateItem :one
UPDATE items
SET name = $2,
    category = $3,
    variant = $4,
    total_quantity = $5,
    description = $6,
    updated_at = NOW()
WHERE id = $1
RETURNING id, name, category, variant, committee_id, total_quantity, description, created_at, updated_at
`

type UpdateItemParams struct {
	ID            int32       `json:"id"`
	Name          string      `json:"name"`
	Category      string      `json:"category"`
	Variant       pgtype.Text `json:"variant"`
	TotalQuantity int32       `json:"total_quantity"`
	Description   pgtype.Text `json:"description"`
}

func (q *Queries) UpdateItem(ctx context.Context, arg UpdateItemParams) (Item, error) {
	row := q.db.QueryRow(ctx, updateItem,
		arg.ID,
		arg.Name,
		arg.Category,
		arg.Variant,
		arg.TotalQuantity,
		arg.Description,
	)
	var i Item
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Category,
		&i.Variant,
		&i.CommitteeID,
		&i.TotalQuantity,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertItem = `-- name: UpsertItem :one
INSERT INTO items (name, category, variant, committee_id, total_quantity, description)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (name, variant, committee_id) DO UPDATE
SET total_quantity = EXCLUDED.total_quantity,
    description = EXCLUDED.description,
    updated_at = NOW()
RETURNING id, name, category, variant, committee_id, total_quantity, description, created_at, updated_at
`

type UpsertItemParams struct {
	Name          string      `json:"name"`
	Category      string      `json:"category"`
	Variant       pgtype.Text `json:"variant"`
	CommitteeID   int32       `json:"committee_id"`
	TotalQuantity int32       `json:"total_quantity"`
	Description   pgtype.Text `json:"description"`
}

func (q *Queries) UpsertItem(ctx context.Context, arg UpsertItemParams) (Item, error) {
	row := q.db.QueryRow(ctx, upsertItem,
		arg.Name,
		arg.Category,
		arg.Variant,
		arg.CommitteeID,
		arg.TotalQuantity,
		arg.Description,
	)
	var i Item
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Category,
		&i.Variant,
		&i.CommitteeID,
		&i.TotalQuantity,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
