// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type BorrowRequest struct {
	ID                 int32              `json:"id"`
	BorrowerName       string             `json:"borrower_name"`
	BorrowerTelegramID int64              `json:"borrower_telegram_id"`
	CommitteeID        int32              `json:"committee_id"`
	BorrowPhotoUrl     string             `json:"borrow_photo_url"`
	ReturnPhotoUrl     string             `json:"return_photo_url"`
	ExpectedReturnAt   pgtype.Date        `json:"expected_return_at"`
	Remarks            pgtype.Text        `json:"remarks"`
	Status             string             `json:"status"`
	BorrowedAt         pgtype.Timestamptz `json:"borrowed_at"`
}

type BorrowRequestItem struct {
	ID               int32 `json:"id"`
	BorrowRequestID  int32 `json:"borrow_request_id"`
	ItemID           int32 `json:"item_id"`
	Quantity         int32 `json:"quantity"`
	ReturnedQuantity int32 `json:"returned_quantity"`
}

type Committee struct {
	ID        int32              `json:"id"`
	Name      string             `json:"name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Item struct {
	ID            int32              `json:"id"`
	Name          string             `json:"name"`
	Category      string             `json:"category"`
	Variant       pgtype.Text        `json:"variant"`
	CommitteeID   int32              `json:"committee_id"`
	TotalQuantity int32              `json:"total_quantity"`
	Description   pgtype.Text        `json:"description"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type User struct {
	ID          int32              `json:"id"`
	TelegramID  int64              `json:"telegram_id"`
	Name        string             `json:"name"`
	Username    pgtype.Text        `json:"username"`
	Role        string             `json:"role"`
	CommitteeID pgtype.Int4        `json:"committee_id"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}
