// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getAllUsers = `-- name: GetAllUsers :many
SELECT id, telegram_id, name, username, role, committee_id, created_at
FROM users
ORDER BY created_at DESC
`

func (q *Queries) GetAllUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.Query(ctx, getAllUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.TelegramID,
			&i.Name,
			&i.Username,
			&i.Role,
			&i.CommitteeID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserByTelegramID = `-- name: GetUserByTelegramID :one
SELECT id, telegram_id, name, username, role, committee_id, created_at
FROM users
WHERE telegram_id = $1
`

func (q *Queries) GetUserByTelegramID(ctx context.Context, telegramID int64) (User, error) {
	row := q.db.QueryRow(ctx, getUserByTelegramID, telegramID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.TelegramID,
		&i.Name,
		&i.Username,
		&i.Role,
		&i.CommitteeID,
		&i.CreatedAt,
	)
	return i, err
}

const updateUserRole = `-- name: UpdateUserRole :one
UPDATE users
SET role = $2, committee_id = $3
WHERE id = $1
RETURNING id, telegram_id, name, username, role, committee_id, created_at
`

type UpdateUserRoleParams struct {
	ID          int32       `json:"id"`
	Role        string      `json:"role"`
	CommitteeID pgtype.Int4 `json:"committee_id"`
}

func (q *Queries) UpdateUserRole(ctx context.Context, arg UpdateUserRoleParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserRole, arg.ID, arg.Role, arg.CommitteeID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.TelegramID,
		&i.Name,
		&i.Username,
		&i.Role,
		&i.CommitteeID,
		&i.CreatedAt,
	)
	return i, err
}
